'$schema' = 'https://starship.rs/config-schema.json'

format = """
$time\
$username\
$hostname\
$directory\
\
$git_branch\
$git_commit\
$git_state\
$git_status\
\
$cmd_duration\
$jobs\
$status\
\
$shell\
$character"""

add_newline = true
continuation_prompt = '[>](bold subtext0) '
palette = "catppuccin_mocha"

[character]
success_symbol = '[λ](text)'
error_symbol = '[λ](red)'

[time]
format = '[$time]($style) '
style = 'fg:mauve'
time_format = "%R"
disabled = false

[directory]
format = '[$path ]($style)[($read_only)]($read_only_style)'
style = 'fg:peach italic'
read_only = '[ro] '
read_only_style = 'fg:red'

[username]
format = '[$user]($style)@'
style_root = 'fg:sapphire'
style_user = 'fg:sapphire'
show_always = true

[hostname]
format = '[$hostname]($style) '
style = 'fg:sapphire'
ssh_only = false

### VCS
[git_branch]
format = '$symbol[$branch ]($style)'
style = 'fg:maroon'
symbol = 'on '
ignore_branches = ['main', 'master']

[git_commit]
format = '[$hash$tag ]($style)'
style = 'fg:maroon'
tag_disabled = false
tag_symbol = ''

[git_state]
format = '[\[$state($progress_current/$progress_total)\] ]($style)'
style = 'fg:maroon'
disabled = false

[git_status]
format = '[$all_status$ahead_behind]($style)'
style = 'fg:maroon'
ahead = '↑${count}'
diverged = '⇕↑${ahead_count}↓${behind_count}'
behind = '↓${count}'
conflicted = 'CONFLICT '
deleted = 'x${count} '
modified = '!${count} '
renamed = '!${count} '
untracked = '?${count} '
staged = '+${count} '
stashed = '*${count} '
disabled = false

[cmd_duration]
format = 'took [$duration]($style) '
style = 'fg:yellow'
show_milliseconds = false
min_time = 1000
disabled = false

[jobs]
disabled = false
symbol = '& '
style = 'fg:yellow'

[status]
format = '[$maybe_int$common_meaning$signal_name]($style) '
pipestatus_format = '\[$pipestatus\] '
pipestatus_segment_format = '[$status]($style)'
style = 'fg:yellow'
map_symbol = false
pipestatus = true
disabled = false

[palettes.catppuccin_mocha]
rosewater = '#f5e0dc'
flamingo = '#f2cdcd'
pink = '#f5c2e7'
mauve = '#cba6f7'
red = '#f38ba8'
maroon = '#eba0ac'
peach = '#fab387'
yellow = '#f9e2af'
green = '#a6e3a1'
teal = '#94e2d5'
sky = '#89dceb'
sapphire = '#74c7ec'
blue = '#89b4fa'
lavender = '#b4befe'
text = '#cdd6f4'
subtext1 = '#bac2de'
subtext0 = '#a6adc8'
overlay2 = '#9399b2'
overlay1 = '#7f849c'
overlay0 = '#6c7086'
surface2 = '#585b70'
surface1 = '#45475a'
surface0 = '#313244'
base = '#1e1e2e'
mantle = '#181825'
crust = '#11111b'
contrast = '#000000'
